// <auto-generated />
using System;
using MessageBroker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessageBroker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MessageBroker.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAfter")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("subscription_id");

                    b.Property<string>("TopicMessage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_message");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MessageBroker.Models.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_id");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MessageBroker.Models.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Topics");
                });
#pragma warning restore 612, 618
        }
    }
}
